version: '3.5'

services:
  postgres:
    container_name: app-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      PGDATA: /data/postgres
    volumes:
      - app-db:/data/postgres
    ports:
      - "5435:5432"
    restart: unless-stopped

networks:
  chat-net:
    driver: bridge

volumes:
  chat-db: